CREATE SCHEMA IF NOT EXISTS tanagra_db CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER dbuser IDENTIFIED BY 'dbpwd';

GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON tanagra_db.* TO 'dbuser'@'%';
