name: Run EXPAND_CONFIG and INDEX_ALL
description: 'For given underlay, run EXPAND_CONFIG and INDEX_ALL. Write index to underlay_nightly dataset.
  Example: In expanded/cms_synpuf.json, index dataset will be temporarily changed from cmssynpuf_index_011523 to
  cms_synpuf_nightly. So cmssynpuf_index_011523 is not disturbed.'

inputs:
  company-and-underlay:
    description: 'Example: broad/cms_synpuf'
    required: true
  index-gcp-project:
    description: 'GCP project containing underlay index'
    required: true
  google-application-credentials-relative-path:
    description: 'Relative path to GOOGLE_APPLICATION_CREDENTIALS file. This file must have been written before this action is called.'
    required: true

runs:
  using: "composite"
  steps:
#    - name: Set up AdoptOpenJDK 11
#      uses: actions/setup-java@v3
#      with:
#        java-version: 11
#        distribution: 'temurin'
#    - name: Cache Gradle packages
#      uses: actions/cache@v2
#      with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#        key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
#        restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
    - name: Run EXPAND_CONFIG
      run: |
         exit 1
#        underlay=$(echo ${{ inputs.company-and-underlay }} | awk -F/ '{print $NF}')
#        cmd="./gradlew indexer:index -Dexec.args=\"EXPAND_CONFIG $(pwd)/service/src/main/resources/config/${{ inputs.company-and-underlay }}/original/${underlay}.json $(pwd)/service/src/main/resources/config/${{ inputs.company-and-underlay }}/expanded\" --scan"
#        echo "Running:  $cmd"
#        eval ${cmd}
#      env:
#        GOOGLE_APPLICATION_CREDENTIALS: ../${{ inputs.google-application-credentials-relative-path }}
#      shell: bash
    - name: Post expand config failure to Slack
      #      if: failure()
      if: always()
      uses: broadinstitute/action-slack@v3.8.0
      # see https://github.com/broadinstitute/action-slack
      with:
        status: ${{ job.status }}
        channel: "#tanagra-engineering"
#        author_name: "EXPAND_CONFIG failed for ${{ inputs.company-and-underlay }}"
        author_name: "Test, please ignore"
        fields: job, commit
#    - name: Delete and create index dataset (underlay_nightly dataset)
#      run: |
#        underlay=$(echo ${{ inputs.company-and-underlay }} | awk -F/ '{print $NF}')
#        index_dataset_name="${underlay}_nightly"
#        gcloud auth activate-service-account --key-file ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
#        bq rm -r -f --project_id ${{ inputs.index-gcp-project }} -d ${index_dataset_name}
#        bq mk --project_id ${{ inputs.index-gcp-project }} -d ${index_dataset_name}
#      env:
#        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google-application-credentials-relative-path }}
#      shell: bash
#    - name: Run INDEX_ALL (will write index to underlay_nightly dataset)
#      run: |
#        underlay=$(echo ${{ inputs.company-and-underlay }} | awk -F/ '{print $NF}')
#        index_dataset_name="${underlay}_nightly"
#        # In underlay.json, change index dataset name to "underlay_nightly"
#        sed -i "s/\"datasetId\" : \"[a-zA-Z0-9_]*index.*\"/\"datasetId\" : \"${index_dataset_name}\"/" service/src/main/resources/config/${{ inputs.company-and-underlay }}/expanded/${underlay}.json
#        echo "underlay json has been changed to index to \"underlay_nightly\":"
#        head service/src/main/resources/config/${{ inputs.company-and-underlay }}/expanded/${underlay}.json
#        cmd="./gradlew indexer:index -Dexec.args=\"INDEX_ALL $(pwd)/service/src/main/resources/config/${{ inputs.company-and-underlay }}/expanded/${underlay}.json\" --scan"
#        echo "Running:  $cmd"
#        eval ${cmd}
#      env:
#        GOOGLE_APPLICATION_CREDENTIALS: ../${{ inputs.google-application-credentials-relative-path }}
#      shell: bash
