tanagra:
  underlay:
    files: [ "broad/aou_synthetic/expanded/aou_synthetic.json", "broad/cms_synpuf/expanded/cms_synpuf.json" ]

  feature:
    artifact-storage-enabled: true

  auth:
    disable-checks: false
    iap-gke-jwt: true
    iap-appengine-jwt: false
    bearer-token: false

  db:
    initialize-on-start: false
    upgrade-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${TANAGRA_DATABASE_NAME}
    username:
    password:

  vumc-admin:
    base-path: https://tanagra-dev.api.verily.com
    oauth-client-id: 694046000181-baqla782scqfaaga26869orhhd8o7vjo.apps.googleusercontent.com
    use-adc: true

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: tanagra
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/api/