tanagra:
  underlay:
    files: [ "broad/aou_synthetic/expanded/aou_synthetic.json", "broad/cms_synpuf/expanded/cms_synpuf.json", "test/plugin/test-no-plugins.json", "test/plugin/test-plugins-configured.json" ]

  feature:
    artifact-storage-enabled: true

  db:
    initialize-on-start: true
    upgrade-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/tanagra_db
    username: dbuser
    password: dbpwd

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: tanagra
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/api/
