tanagra:
  underlay:
    files: [ "cmssynpuf_broad", "aouSR2019q4r4_broad" ]

  feature:
    artifact-storage-enabled: true
    activity-log-enabled: true

  auth:
    disable-checks: false
    iap-gke-jwt: true
    iap-appengine-jwt: false
    bearer-token: false

  db:
    initialize-on-start: false
    upgrade-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${TANAGRA_DATABASE_NAME}
    username:
    password:

  access-control:
    model: OPEN_ACCESS # VUMC_ADMIN, VERILY_GROUP
    params: []
    base-path:
    oauth-client-id:

  export:
    shared:
      gcp-project-id: broad-tanagra-dev
      bq-dataset-ids: service_export_us, service_export_uscentral1
      gcs-bucket-names: broad-tanagra-dev-bq-export
    models:
      -
        type: INDIVIDUAL_FILE_DOWNLOAD
      -
        type: IPYNB_FILE_DOWNLOAD
      -
        type: VWB_FILE_IMPORT
        redirect-away-url: https://terra-devel-ui-terra.api.verily.com/import?urlList=${tsvFileUrl}&returnUrl=${redirectBackUrl}&returnApp=Tanagra

logging.pattern.level: '%X{requestId} %5p'
logging.level.bio.terra.tanagra: DEBUG

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: tanagra
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/api/
