tanagra:
  underlay:
    # TODO(tjennison): Split these for different environments.
    underlay-yaml-files: ["underlays/aou_synthetic.yaml", "underlays/synpuf.yaml", "underlays/sd.yaml", "underlays/test/aou_synthetic.yaml"]
    underlay-files: [ "broad/aou_synthetic/expanded/aou_synthetic.json", "broad/cms_synpuf/expanded/cms_synpuf.json" ]

  feature:
    artifact-storage-enabled: true

  db:
    initialize-on-start: false
    upgrade-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/tanagra_db
    username:
    password:

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: workspace
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/api/
