# Dummy github action to allow iteration.

name: Build & Push API image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to tag the image with, e.g. "1.2.3"'
        required: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
