name: Diff Releases

on:
  workflow_dispatch:
    inputs:
      first-release-tag:
        description: 'First release tag (e.g. 0.0.365)'
        required: true
        default: 0.0.365
      last-release-tag:
        description: 'Last release tag (e.g. 0.0.370)'
        required: true
        default: 0.0.370
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate git log diff file between two releases
        run: |
          git status
          git diff 0.0.365..0.0.370 -- underlay/ indexer/
          git diff "$first_release..$last_release" -- underlay/ indexer/
          .github/tools/diffReleases.sh $FIRST_RELEASE_TAG $LAST_RELEASE_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_RELEASE_TAG: ${{ github.event.inputs.first-release-tag }}
          LAST_RELEASE_TAG: ${{ github.event.inputs.last-release-tag }}
      - name: Save diff file
        uses: actions/upload-artifact@v4
        with:
          name: diff-file
          path: diffReleases.txt
          retention-days: 1
