# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Check Generated Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
    # Always run this GHA on PRs, so that we have at least one successful check to satisfy branch protections.
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AdoptOpenJDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Regenerate documentation and Typescript files and check for changes
        run: .github/tools/checkGeneratedFiles.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
