# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Indexer Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AdoptOpenJDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Pull credentials
        id: pull_credentials
        run: |
          # For security reasons, Broad prefers we read GHA secrets instead of reading from vault.
          # This step does the equivalent of the pull-credentials.sh script.
          # On local machines, the script fetches a SA from Vault.
          # In GH actions, the SA key is stored in a GH repo secret.
          # Regardless of how it was fetched, tests and scripts expect these
          # keys to be stored in rendered/.
          mkdir -p rendered/broad/
          echo "$TEST_PROJECT_SA_KEY" > rendered/broad/tanagra_sa.json
        env:
          TEST_PROJECT_SA_KEY: ${{ secrets.TEST_PROJECT_SA_KEY }}
#      - name: Create Maven settings file
#        uses: s4u/maven-settings-action@v2.8.0
#        with:
#          servers: '[{"id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}"}]'
      - name: Gradle Build and Check
        # The check task includes the build, test and static analysis tasks.
        run: ./gradlew indexer:check --scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ../rendered/broad/tanagra_sa.json
