# Run EXPAND_CONFIG, INDEX_ALL every night, for all Broad underlays. Even if there are no commits, this will
# run every night and catch problems.
# Writes index to "nightly" dataset, eg aou_synthetic_nightly.
name: Nightly tests

on:
  workflow_dispatch:
  schedule:
  - cron: '0 7 * * *' # 7AM UTC = 2AM EST

jobs:
  test:
    strategy:
      matrix:
        company-and-underlay: [ "broad/aou_synthetic", "broad/cms_synpuf" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull credentials
      id: pull_credentials
      run: |
        # For security reasons, Broad prefers we read GHA secrets instead of reading from vault.
        # This step does the equivalent of the pull-credentials.sh script.
        # On local machines, the script fetches a SA from Vault.
        # In GH actions, the SA key is stored in a GH repo secret.
        # Regardless of how it was fetched, tests and scripts expect these
        # keys to be stored in rendered/.
        mkdir -p rendered/broad/
        echo "$TEST_PROJECT_SA_KEY" > rendered/broad/tanagra_sa.json
      env:
        TEST_PROJECT_SA_KEY: ${{ secrets.TEST_PROJECT_SA_KEY }}
    - name: Expand config and index
      # If one underlay fails, keep running the other ones
      if: always()
      uses: ./.github/actions/expand-config-and-index
      with:
        company-and-underlay: ${{ matrix.company-and-underlay }}
        index-gcp-project: broad-tanagra-dev
        google-application-credentials-relative-path: rendered/broad/tanagra_sa.json
      secrets:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}