# Run EXPAND_CONFIG, INDEX_ALL every night. Even if there are no commits, this will
# run every night and catch problems.
name: Nightly tests

on:
  workflow_dispatch:
  schedule:
  - cron: '0 7 * * *' # 7AM UTC = 2AM EST

env:
  INDEX_PROJECT: "broad-tanagra-dev"

jobs:
  test:
    strategy:
      matrix:
        company_and_underlay: [ "broad/aou_synthetic", "broad/cms_synpuf" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up AdoptOpenJDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
    - name: Pull credentials
      id: pull_credentials
      run: |
        # For security reasons, Broad prefers we read GHA secrets instead of reading from vault.
        # This step does the equivalent of the pull-credentials.sh script.
        # On local machines, the script fetches a SA from Vault.
        # In GH actions, the SA key is stored in a GH repo secret.
        # Regardless of how it was fetched, tests and scripts expect these
        # keys to be stored in rendered/.
        mkdir -p rendered/broad/
        echo "$TEST_PROJECT_SA_KEY" > rendered/broad/tanagra_sa.json
      env:
        TEST_PROJECT_SA_KEY: ${{ secrets.TEST_PROJECT_SA_KEY }}
#    - name: Expand config
#      run: |
#        underlay=$(echo ${{ matrix.company_and_underlay }} | awk -F/ '{print $NF}')
#        cmd="./gradlew indexer:index -Dexec.args=\"EXPAND_CONFIG $(pwd)/service/src/main/resources/config/broad/aou_synthetic/original/aou_synthetic.json $(pwd)/service/src/main/resources/config/broad/aou_synthetic/expanded\""
#        echo "Running:  $cmd"
#        eval ${cmd}
##      env:
##        GOOGLE_APPLICATION_CREDENTIALS: ../rendered/broad/tanagra_sa.json
    - name: Delete and create index dataset
      run: |
        underlay=$(echo ${{ matrix.company_and_underlay }} | awk -F/ '{print $NF}')
        index_dataset_name="${underlay}_nightly"
        gcloud auth activate-service-account --key-file ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        bq rm -r -f -d ${{ env.INDEX_PROJECT }}.${index_dataset_name}
        bq mk ${{ env.INDEX_PROJECT }}.${index_dataset_name}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: rendered/broad/tanagra_sa.json

