# Run EXPAND_CONFIG, INDEX_ALL every night. Even if there are no commits, this will
# run every night and catch problems.
# Writes index to "nightly" dataset, eg aou_synthetic_nightly.
name: Nightly tests

on:
  workflow_dispatch:
    inputs:
      company-and-underlay:
        required: true
        type: string
      index-gcp-project:
        required: true
        type: string
      google-application-credentials-relative-path:
        required: true
        type: string
  schedule:
  - cron: '0 7 * * *' # 7AM UTC = 2AM EST

env:
  INDEX_PROJECT: "broad-tanagra-dev"

jobs:
  test:
    strategy:
      matrix:
        company-and-underlay: [ "broad/aou_synthetic", "broad/cms_synpuf" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - name: Set up AdoptOpenJDK 11
#      uses: actions/setup-java@v3
#      with:
#        java-version: 11
#        distribution: 'temurin'
#    - name: Cache Gradle packages
#      uses: actions/cache@v2
#      with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#        key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
#        restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
    - name: Pull credentials
      id: pull_credentials
      run: |
        # For security reasons, Broad prefers we read GHA secrets instead of reading from vault.
        # This step does the equivalent of the pull-credentials.sh script.
        # On local machines, the script fetches a SA from Vault.
        # In GH actions, the SA key is stored in a GH repo secret.
        # Regardless of how it was fetched, tests and scripts expect these
        # keys to be stored in rendered/.
        mkdir -p rendered/broad/
        echo "$TEST_PROJECT_SA_KEY" > rendered/broad/tanagra_sa.json
      env:
        TEST_PROJECT_SA_KEY: ${{ secrets.TEST_PROJECT_SA_KEY }}
    - name: Expand config and index
      uses: ./.github/actions/expand-config-and-index
      with:
        company-and-underlay: ${{ matrix.company-and-underlay }}
        index-gcp-project: broad-tanagra-dev
        google_application_credentials_relative_path: rendered/broad/tanagra_sa.json

#    - name: Setup tmate session
#      if: always()
#      uses: mxschmitt/action-tmate@v3
#      env:
#        GOOGLE_APPLICATION_CREDENTIALS: ../rendered/broad/tanagra_sa.json

