# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Service Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MARIADB_ROOT_PASSWORD: rootpwd
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up AdoptOpenJDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Initialize MariaDB
        run: mysql -h 127.0.0.1 -u root -p rootpwd -f ./service/local-dev/local-mariadb-init.sql mariadb
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Pull credentials
        id: pull_credentials
        run: |
          # For security reasons, Broad prefers we read GHA secrets instead of reading from vault.
          # This step does the equivalent of the pull-credentials.sh script.
          # On local machines, the script fetches a SA from Vault.
          # In GH actions, the SA key is stored in a GH repo secret.
          # Regardless of how it was fetched, tests and scripts expect these
          # keys to be stored in rendered/.
          mkdir -p rendered/broad/
          echo "$TEST_PROJECT_SA_KEY" > rendered/broad/tanagra_sa.json
        env:
          TEST_PROJECT_SA_KEY: ${{ secrets.TEST_PROJECT_SA_KEY }}
      - name: Gradle Build and Check
        # The check task includes the build, test and static analysis tasks.
        run: ./gradlew service:check --scan
        env:
#          DBMS: mariadb
          TANAGRA_DB_URL: jdbc:mariadb://127.0.0.1:3306/tanagra_db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ../rendered/broad/tanagra_sa.json
      - name: Jib build
        # Check that jib builds a docker container.
        run: ./gradlew service:jibDockerBuild --scan
