name: Run UI Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run codegen
          start: npm run fake
          wait-on: "http://localhost:3000"
          working-directory: ui
