name: Run UI Unit Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
    - 'README.md'
    - 'docs/**'
  workflow_dispatch:

jobs:
  ui-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    strategy:
      matrix:
        node-version: [ lts/iron ]

    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
    - name: Checkout current code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run codegen
      run: npm run codegen

    - name: Run build
      run: npm run build --if-present

    - name: Run test
      run: npm test
