name: Run UI Unit Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    strategy:
      matrix:
        node-version: [lts/iron]

    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run codegen
      - run: npm run build --if-present
      - run: npm test
