name: Run Workflow Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Gradle Build Workflow
        # The build task includes the test and some quality static analysis tasks.
        run: ./gradlew workflow:build
      - name: Gradle Check
        # The check task runs static analysis on main & test sources.
        run: ./gradlew workflow:check
      - name: Jib build
        # Check that jib builds a docker container.
        run: ./gradlew workflow:jibDockerBuild
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test Reports
          path: workflow/build/reports
      - name: Upload Jacoco Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: workflow/build/jacoco
